lab02/encuesta/urls.py
from django.urls import path

from . import views

app_name = 'encuesta'


urlpatterns = [
    #ex: /encuesta/
    path('', views.index, name='index'),
    path('enviar', views.enviar, name='enviar'),
    
]

lab02/lab02/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('encuesta/', include('encuesta.urls')),
    path('operacion/', include('seramio.urls')),
    path('admin/', admin.site.urls),
]

lab02/seramio/urls.py
from django.urls import path

from . import views

app_name = 'cilindro'
app_name = 'calcular'
urlpatterns = [
    #ex: /encuesta/
    path('', views.vista, name='ejere1'),
    path('volumen', views.pops, name='ejere2'),
    path('resultado', views.ejer1, name='ejer1'),

    path('analizar', views.ejer2, name='ejer2'),
]

lab02/encuesta/models.py
from django.db import models

# Create your models here.

lab02/seramio/models.py
from django.db import models

# Create your models here.

lab02/encuesta/views.py
from multiprocessing import context
from django.shortcuts import render

def index(request):
    context ={
        'titulo' : "Formulario",
    }
    return render(request, 'encuesta/formulario.html', context)

def enviar(request):
    context = {
        'titulo': "Respuesta",
        'nombre' : request.POST[ 'nombre'],
        'clave': request.POST[ 'password'],
        'educacion': request.POST[ 'educacion'],
        'nacionalidad': request.POST['nacionalidad'],
        'idiomas': request.POST.getlist('idiomas'),
        'correo': request.POST['email'],
        'website': request.POST[ 'sitioweb'],
    }
    return render(request, 'encuesta/respuesta.html', context)

lab02/seramio/views.py
from django.shortcuts import render

def vista(request):
    context ={
        'titulo' : "Calculadora Simple",
    }
    return render(request, 'seramio/primer.html', context)


def pops(request):
    context ={
        'titulo' : "Calculadora Cilindro",
    }
    return render(request, 'seramio/segundo.html', context)


def ejer1(request):
    context = {
        'titulo': 'Calculadora simple',
        'n1' : request.POST[ 'n1'],
        'n2': request.POST[ 'n2'],
        'operaciones': request.POST[ 'operaciones'],
        'resultado':request.POST['resultado'],
    }
    return render(request, 'seramio/rpta1.html', context)

def ejer2(request):
    context = {
        'titulo': 'Calculo de volumen de un cilindro',
        'n1' : request.POST[ 'n1'],
        'n2' : request.POST[ 'n2'],
        'radio' : 3.14,
        'resultado':request.POST['resultado'],
    }
    return render(request, 'seramio/rpta2.html', context)

lab02/encuesta/templates/encuesta/formulario.html
<h2>{{titulo}}  </h2>
<form action="{% url 'encuesta:enviar' %}" method="post">
    {%csrf_token %}
    Nombre:
    <input type="text" name="nombre" maxlength="50"><br>
    Contraseña:
    <input type="password" name="password"><br>
    Educacion:
    <select name="educacion">
        <option value="sin-estudios">Sin estudios</option>
        <option value="educacion-obligatoria" selected="selected">Educación Obligatoria</option>
        <option value="formacion-profesional">Formación profesional</option>
        <option value="universidad">Universidad</option>
    </select> <br>

    Nacionalidad:
    <input type="radio" name="nacionalidad" value="hispana">Hispana</input> 
    <input type="radio" name="nacionalidad" value="otra">Otra</input><br>

    Idiomas:
    <input type="checkbox" name="idiomas" value="español">Español</input>
    <input type="checkbox" name="idiomas" value="Inglés">Inglés</input>
    <input type="checkbox" name="idiomas" value="francés">Francés</input>
    <input type="checkbox" name="idiomas" value="aleman">Alemán</input><br>
    Email:
    <input type="text" name="email"><br>
    Sitio Web:
    <input type="text" name="sitioweb"><br>
    // Botón de enviar
    <input type="submit" name="submit" value="Enviar">
</form>

lab02/encuesta/templates/encuesta/respuesta.html
<h2>{{ titulo}}</h2>
<p>Nombre: {{ nombre }}</p>
<p>Clave: {{clave}} </p>
<p>Educación: {{educacion}}</p>
<p>»Nacionalidad: {{nacionalidad}}</p>
<p>Idiomas:</p>
<ul>
    {% for item in idiomas %}
    <li>{{ item }}</1i>
    {% endfor %}
</u1>
<p>Email: {{ correo }}</p>
<p>Sitio Web: {{website}} </p>

lab02/seramio/templates/seramio/primer.html
<h2>Primer Ejercicio </h2>
<form action="{% url 'calcular:ejer1' %}" method="post">
    {% csrf_token %}



    <script>
       function vol(){
        var signio = document.getElementById('op').value;
        if (signio == "+"){
            var numero1 = document.getElementById('n1').value;
            var numero2 = document.getElementById('n2').value;
            var resultado = Number(numero1) + Number(numero2);
            document.getElementById('resultado').value= resultado;

        }
        else if (signio == "-"){
            var numero1 = document.getElementById('n1').value;
         var numero2 = document.getElementById('n2').value;
         var resultado = numero1 - numero2;
         document.getElementById('resultado').value= resultado;

        }
        else if(signio == "/"){
            var numero1 = document.getElementById('n1').value;
         var numero2 = document.getElementById('n2').value;
         var resultado = numero1 / numero2;
         document.getElementById('resultado').value= resultado;

        }
        else{
            var numero1 = document.getElementById('n1').value;
         var numero2 = document.getElementById('n2').value;
         var resultado = numero1 * numero2;
         document.getElementById('resultado').value= resultado;
        }
       } 
       
    
</script>





Operacion a realizar:
<select name="operaciones" id="op">
    <option value="+" >Suma</option>
    <option value="-" selected="selected">Resta</option>
    <option value="/">Division</option>
    <option value="*">Multiplicacion</option>
</select> <br>






    <br>
    Ingrese el primer numero:
    <input  type="number" name="n1" id="n1" onkeyup="vol();" ><br>
    <br>
    Ingrese el segundo numero:
    <input type="number" name="n2" id="n2" onkeyup="vol();"><br>
   
    <br>
  

    <input  type="number" name="resultado" id="resultado" step="0.01"><br>


    <input type="submit" name="calcular" value="Calcular">
</form>

lab02/seramio/templates/seramio/rpta1.html
<h2>{{ titulo}}</h2>

<h3>El resultado de {{n1}} {{operaciones}} {{n2}} es  {{resultado}}</h3>

lab02/seramio/templates/seramio/rpta2.html
<h2>{{ titulo}}</h2>

<p> El volumen del Cilindro es de: {{resultado}} metros cubicos</p>

lab02/seramio/templates/seramio/segundo.html
<h2> {{ titulo}}</h2>

<form action="{% url 'cilindro:ejer2' %}" method="post">

    {% csrf_token %}
    <script>
        function vol(){
          var radio = document.getElementById('radio').value;
          var altura = document.getElementById('altura').value;
          var pi= 3.14
          var volumen= pi* (radio* radio)*altura 
          document.getElementById('resultado').value= volumen;
    
        }
        </script>
 


    <br>
    Ingrese el diametro(en metros):
    <input  type="number" name="n1" id="radio"onkeyup="vol();"><br>
    <br>
    Ingrese la altura (en metros):
    <input type="number" name="n2" id="altura"onkeyup="vol();"><br>
   
    <br>
    <div hidden>
        <input type="number" name="resultado" id="resultado" step="0.01"><br>
    </div>

    
    <input type="submit" name="ejer2" value="Calcular" >



    
    
</form>